# Server Configuration
server:
  address: "localhost"
  port: "8080"

# Database Configuration (example)
database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "mydb"